version: "3.9"
services:
  notubot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres
    environment:
      - POSTGRES_DB=notubot
      - POSTGRES_USER=USERNAME
      - POSTGRES_PASSWORD=PASSWORD
    ports:
      - 5432:5432
    restart: always
