#!/usr/bin/env python3
# python3 -m pip install --upgrade https://github.com/LonamiWebs/Telethon/archive/master.zip
from subprocess import check_call
from sys import executable

try:
    import telethon as tl
except (ImportError, ModuleNotFoundError):
    print("Installing the module...")
    check_call(
        [executable, "-m", "pip", "install", "--upgrade", "https://github.com/LonamiWebs/Telethon/archive/master.zip"]
    )
finally:
    import telethon as tl


print("Get your API ID and API HASH from my.telegram.org or @ScrapperRoBot to proceed.\n\n")

try:
    API_ID = int(input("Please enter your API ID: "))
except ValueError:
    print("APP ID must be an integer.\nQuitting...")
    exit(0)
API_HASH = input("Please enter your API HASH: ")

client = tl.TelegramClient(tl.sessions.StringSession(), api_id=API_ID, api_hash=API_HASH)


async def main() -> None:
    try:
        print("Generating a user STRING_SESSION...")
        string_session = client.session.save()

        print(string_session)
        await client.send_message(
            "me",
            f"Generated by @notudope\n\n<code>STRING_SESSION</code>: <code>{string_session}</code>\n\n<b>⚠️ PLEASE BE CAREFUL, DO NOT SHARE THIS MESSAGE TO OTHER PEOPLE IN TELEGRAM !!</b>",
            parse_mode="html",
        )

        print(
            'Your SESSION has been generated. Check your Telegram "Saved Messages" to copy STRING_SESSION or copy from above.'
        )
        exit(0)
    except tl.errors.rpcerrorlist.ApiIdInvalidError:
        print("Your API ID/API HASH combination is invalid. Kindly recheck.\nQuitting...")
        exit(0)
    except ValueError:
        print("API HASH must not be empty!\nQuitting...")
        exit(0)
    except tl.errors.rpcerrorlist.PhoneNumberInvalidError:
        print("The phone number is invalid!\nQuitting...")
        exit(0)


with client:
    client.loop.run_until_complete(main())
